#!/bin/bash

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║       LABDOCK — Avaliação de Desempenho de Sistemas      ║"
echo "║           Lab 01 — Benchmarking de CPU e Memória         ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "  Bem-vindo(a) ao ambiente de laboratório!"
echo ""
echo "  Neste lab você vai:"
echo "   → Executar benchmarks de CPU e memória"
echo "   → Coletar métricas sob diferentes cargas"
echo "   → Exportar resultados em CSV"
echo "   → Visualizar os dados em gráficos no Google Sheets"
echo ""
echo "  Para começar, execute:"
echo "    ./benchmark.sh"
echo ""
echo "  Consulte o README.md ou o PDF para ver todos os exercícios."
echo ""