#!/bin/bash

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║   LABDOCK — Avaliação de Desempenho de Sistemas (2026.2) ║"
echo "║       Lab 02 — Compressão e Intervalos de Confiança      ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "  Bem-vindo(a) ao ambiente de laboratório!"
echo ""
echo "  Para começar, execute:"
echo "    ./scripts/gerar_datasets.sh"
echo "    ./scripts/executar_experimento.sh dados 10"
echo ""
echo "  Depois, analise os resultados com:"
echo "    python3 scripts/analisar_resultados.py resultados/experimento.csv"
echo ""
echo "  Consulte o roteiro guiado para ver todos os exercícios."
echo ""
