services:
  avd2026-2-lab-02:
    build: .
    container_name: avd2026-2-lab-02
    volumes:
      - ./scripts/setup.sh:/etc/profile.d/setup.sh
      - ./dados:/lab/dados
      - ./resultados:/lab/resultados
    stdin_open: true
    tty: true
    command: ["/bin/bash", "--login"]
