#!/bin/bash

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║       LABDOCK — Avaliação de Desempenho de Sistemas      ║"
echo "║      Lab 02 — Throughput e Latência com Apache Bench     ║ "
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "  Bem-vindo(a) ao ambiente de laboratório!"
echo ""
echo "  Neste lab você vai:"
echo "   → Subir um servidor web Apache"
echo "   → Simular requisições HTTP com Apache Bench"
echo "   → Medir throughput e latência sob diferentes cargas"
echo "   → Visualizar os resultados no Datawrapper"
echo ""
echo "  Para começar, execute:"
echo "    ./benchmark_web.sh"
echo ""
echo "  Consulte o README.md ou o PDF para ver todos os exercícios."
echo ""