#!/bin/bash

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║              LABDOCK — Sistemas Operacionais             ║"
echo "║         Lab 02 — Sistema de Arquivos e Permissões        ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "  Bem-vindo(a) ao ambiente de laboratório!"
echo ""
echo "  Ferramentas disponíveis:"
echo "   → ls        — listar arquivos e diretórios"
echo "   → tree      — visualizar estrutura de diretórios"
echo "   → chmod     — alterar permissões de arquivos"
echo "   → chown     — alterar dono de arquivos"
echo "   → df        — verificar uso de disco"
echo "   → du        — verificar tamanho de diretórios"
echo ""
echo "  Usuários criados neste lab:"
echo "   → aluno      — usuário comum"
echo "   → visitante  — usuário com acesso limitado"
echo ""
echo "  Consulte o README.md ou o PDF para ver todos os exercícios."
echo ""
