#!/bin/bash

echo "========================================"
echo "  LabDock — SO Lab 02"
echo "  Sistema de Arquivos e Permissões"
echo "========================================"
echo ""
echo "Ferramentas disponíveis:"
echo "  ls          — listar arquivos e diretórios"
echo "  tree        — visualizar estrutura de diretórios"
echo "  chmod       — alterar permissões de arquivos"
echo "  chown       — alterar dono de arquivos"
echo "  df          — verificar uso de disco"
echo "  du          — verificar tamanho de diretórios"
echo ""
echo "Usuários criados neste lab:"
echo "  aluno       — usuário comum"
echo "  visitante   — usuário com acesso limitado"
echo ""
echo "Para começar, leia o README.md:"
echo "  cat README.md"
echo ""