#!/bin/bash

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║       LABDOCK — Avaliação de Desempenho de Sistemas      ║"
echo "║                Lab 03 — Simulação de Filas               ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "  Bem-vindo(a) ao ambiente de laboratório!"
echo ""
echo "  Neste lab você vai:"
echo "   → Simular chegada de clientes em uma fila M/M/1"
echo "   → Observar o comportamento do sistema sob diferentes cargas"
echo "   → Medir tempo de espera, tamanho da fila e utilização"
echo "   → Visualizar os resultados no Datawrapper"
echo ""
echo "  Para começar, execute:"
echo "    ./rodar_simulacao.sh"
echo ""
echo "  Consulte o README.md ou o PDF para ver todos os exercícios."
echo ""