#!/bin/bash

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║              LABDOCK — Redes de Computadores             ║"
echo "║               Lab 01 — Cliente-Servidor TCP              ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "  Bem-vindo(a) ao ambiente de laboratório!"
echo ""
echo "  Neste lab você vai:"
echo "   → Estabelecer uma conexão TCP entre cliente e servidor"
echo "   → Observar o handshake TCP com tcpdump"
echo "   → Simular a queda do servidor e ver o impacto"
echo "   → Testar conexões com netcat"
echo ""
echo "  Para começar, execute:"
echo "    python3 client.py"
echo ""
echo "  Consulte o README.md para ver todos os exercícios."
echo ""