#!/bin/bash

echo "========================================"
echo "  LabDock — SO Lab 01"
echo "  Gerenciamento de Processos"
echo "========================================"
echo ""
echo "Ferramentas disponíveis:"
echo "  htop        — monitor interativo de processos"
echo "  ps          — listar processos"
echo "  kill        — encerrar processos por PID"
echo "  stress-ng   — simular carga no sistema"
echo ""
echo "Para começar, leia o README.md:"
echo "  cat README.md"
echo ""