#!/bin/bash

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║              LABDOCK — Sistemas Operacionais             ║"
echo "║             Lab 01 — Gerenciamento de Processos          ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "  Bem-vindo(a) ao ambiente de laboratório!"
echo ""
echo "  Ferramentas disponíveis:"
echo "   → htop       — monitor interativo de processos"
echo "   → ps         — listar processos"
echo "   → kill       — encerrar processos por PID"
echo "   → stress-ng  — simular carga no sistema"
echo ""
echo "  Para começar, leia o README.md:"
echo "    cat README.md"
echo ""
