#!/bin/bash

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║              LABDOCK — Sistemas Operacionais             ║"
echo "║     Lab 03 — Escalonamento e Prioridade de Processos     ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "  Bem-vindo(a) ao ambiente de laboratório!"
echo ""
echo "  Ferramentas disponíveis:"
echo "   → nice       — iniciar um processo com prioridade definida"
echo "   → renice     — alterar prioridade de um processo em execução"
echo "   → htop       — monitorar processos e prioridades em tempo real"
echo "   → stress-ng  — simular carga de CPU"
echo "   → ps         — listar processos com suas prioridades"
echo ""
echo "  Conceito de prioridade no Linux:"
echo "   → Valores de nice: -20 (maior prioridade) até 19 (menor prioridade)"
echo "   → Padrão: 0"
echo ""
echo "  Para começar, leia o README.md:"
echo "    cat README.md"
echo ""
