services:
  avd-lab-01:
    build: .
    container_name: avd-lab-01
    volumes:
      - ./scripts/setup.sh:/etc/profile.d/setup.sh
      - ./resultados:/lab/resultados
    stdin_open: true
    tty: true
    command: ["/bin/bash", "--login"]