services:
  so-lab-01:
    build: .
    container_name: so-lab-01
    volumes:
      - ./scripts/setup.sh:/etc/profile.d/setup.sh
    stdin_open: true
    tty: true
    command: ["/bin/bash", "--login"]
